### Site Settings ###
title               : Rafael F. Ribeiro | Data Science e IA
description         : >-                               # >- means to ignore newlines until "url:"
                      Um cara curioso!.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/webpage"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
#repository          : rfribeiro/webpage    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Rafael F. Ribeiro
  image             : https://avatars3.githubusercontent.com/u/5655897?s=400&u=791c4fa500f516e25eca88ec877865e352db9847&v=4
#  behance           : rfribeiro
# dribbble          : your_username
  email             : rfribeiro@gmail.com
#  facebook          : your_username
  github            : rfribeiro
# gitlab            : your_username
# instagram         : your_username
  linkedin          : rafael-ribeiro-9a248211
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 10
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Tracker
analytics: UA-83979019-1

# Comments
disqus: yes
disqus-shortname: rfribeiro

### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock